config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  concern :viewable do |options|
    collection do
      resources :views, only: [:new,:create,:show,:update,:destroy], defaults: options
    end
  end

  concern :commentable do |options|
      resources :comments, only: [:create,:destroy]
  end

  resources :churches
  resources :people do
    concerns :viewable, applies_to: 'person'
    concerns :commentable
  end

  namespace :admin do
    resource :people_fields, only: [:show,:update]
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

end

app/models/person.rb
# -*- encoding : utf-8 -*-
class Person < ActiveRecord::Base
    include CustomFields
    include Viewable
    include Commentable
    belongs_to :church

    validates :church, presence: true
    validates :first_name, presence: true
    validates :last_name, presence: true


    def name
        "#{first_name} #{last_name}"
    end
end

app/controllers/people_controller.rb
# -*- encoding : utf-8 -*-
class PeopleController < ApplicationController
  before_action :require_church!

  def index
    @views = View.where(church: current_user.church, applies_to: 'person').order(:name)
    @current_view = View.find_by(id: params[:view]) || @views.first || View.new(church: current_user.church, applies_to: 'person')

    @people = Person.where_view(@current_view).page(params[:page])
  end

  def new
    @person = Person.new(church: current_user.church)
  end

  def create
    @person = Person.new(person_params)
    @person.church = current_user.church
    @person.fields_from_params(params[:fields])
    if @person.save
      redirect_to people_path
    else
      render 'new'
    end
  end

  def edit
    @person = find(params[:id])
    if (!@person)
      not_found
    else
      @comments = @person.comments.all
      @comment = @person.comments.build
    end
  end

  def update
    @person = find(params[:id])
    if !@person then
      not_found
    else
      @person.fields_from_params(params[:fields])
      if @person.update(person_params)
        redirect_to people_path
      else
        render 'edit'
      end
    end
  end

  private
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end

    def find(id)
      Person.find_by({ id: id, church: current_user.church })
    end
end

app/helpers/people_helper.rb
# -*- encoding : utf-8 -*-
module PeopleHelper
    def active_view?(view)
        Rails.logger.info view.id
        !@current_view.nil? && @current_view.id == view.id
    end
end

app/views/people/_form.html.erb
<%= render_errors(@person) %>
<%= form_for @person do |f| %>
	<div class="row">
		<div class="col-xs-6">
		  <div class="form-group">
		    <%= f.label :first_name %>
		    <%= f.text_field :first_name, class: 'form-control' %>
		  </div>
	    </div>

		<div class="col-xs-6">
			<div class="form-group">
				<%= f.label :last_name %>
				<%= f.text_field :last_name, class: 'form-control' %>
			</div>
		</div>
	</div>

	<% @person.field_definitions.each do |field| %>
		<div class="row">
			<div class="col-xs-12">
				<div class="form-group">
					<%= render_field_label field %>
					<%= render_field field, @person, class: 'form-control' %>
				</div>
			</div>
		</div>
	<% end %>

 	<div class="row">
	  <div class="col-xs-12">
		  <div class="form-group">
		    <%= f.submit class: 'btn btn-primary pull-right' %>
			<%= link_to 'Back', people_path %>
		  </div>
	  </div>
	</div>
<% end %>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= render "form" %>

<h2>Notes</h2>
<%= render 'comments/list' %>

app/views/people/index.html.erb
<ul class="nav nav-pills views">
	<% @views.each do |view| %>
		<li role="presentation" <% if active_view? view %>class="active"<% end %>><a href="<%= people_path %>?view=<%= view.id %>"><%= view.name %></a></li>
	<% end %>
	<li role="presentation"><a href="<%= new_view_path %>">+</a></li>
</ul>
<br>
<table class="table table-striped people">
  <tr>
      <th>Name</th>
      <% @current_view.load_fields.each do |field| %>
        <th><%= field[:name] %></th>
      <% end %>
	  <th>Notes</th>
  </tr>

  <% @people.each do |person| %>
    <tr>
        <td><%= link_to person.name, edit_person_path(person), class: 'name' %></td>
        <% @current_view.load_fields.each do |field| %>
            <td><%= person.fields.nil? ? '' : person.fields[field[:id]] %></td>
        <% end %>
		<td><%= recent_comments person %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @people %>
<p>
	<% if !@current_view.id.nil? %>
		<%= link_to 'Edit View', view_path(@current_view), class: 'btn btn-default pull-right' %>
	<% end %>
	<%= link_to 'Add', new_person_path, class: 'btn btn-default' %>
</p>

app/views/people/new.html.erb
<h1>Add Person</h1>
<%= render "form" %>