config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  concern :viewable do |options|
    collection do
      resources :views, only: [:new,:create,:show,:update,:destroy], defaults: options
    end
  end

  concern :commentable do |options|
      resources :comments, only: [:create,:destroy]
  end

  resources :churches
  resources :people do
    concerns :viewable, applies_to: 'person'
    concerns :commentable
  end

  namespace :admin do
    resource :people_fields, only: [:show,:update]
  end

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/logout', to: 'sessions#destroy', via: [:get, :post]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">        
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>River</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
		  River
      </a>
    </div>
	  
	<div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'welcome' %>"><%= link_to 'Home', root_path %></li>
		<% if signed_in? && current_user.church %>
			<li class="<%= 'active' if params[:controller] == 'people' %>"><%= link_to 'People', people_path %></li>
			<li class="<%= 'active' if params[:controller] == 'admin_people_fields' %>"><%= link_to 'Admin', admin_people_fields_path %></li>
		<% end %>
	  </ul>
	  <div class="pull-right">
		  <% if signed_in? %>
		  	<p class="navbar-text">Hello <%= current_user.name %></p>
		  	<%= link_to 'Log Out', logout_path, class: 'btn btn-primary navbar-btn logout' %>
		  <% else %>
		    <%= link_to 'Log In', '/auth/developer', class: 'btn btn-primary navbar-btn login' %>
		  <% end %>
	  </div>
    </div>
  </div>
</nav>
<div class="container-fluid">
	<div><%= flash_messages %></div>
	<%= content_for?(:content) ? yield(:content) : yield %>
</div>
</body>
</html>